//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP_ConversorMoneda.WSConvertidor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSConvertidor.ConversorMonedaSoap")]
    public interface ConversorMonedaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_USD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double MXN_USD(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_USD", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MXN_USDAsync(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_COP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double MXN_COP(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_COP", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MXN_COPAsync(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_EUR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double MXN_EUR(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MXN_EUR", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MXN_EURAsync(double MXN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_MXN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double USD_MXN(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_MXN", ReplyAction="*")]
        System.Threading.Tasks.Task<double> USD_MXNAsync(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_COP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double USD_COP(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_COP", ReplyAction="*")]
        System.Threading.Tasks.Task<double> USD_COPAsync(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_EUR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double USD_EUR(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD_EUR", ReplyAction="*")]
        System.Threading.Tasks.Task<double> USD_EURAsync(double USD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_MXN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double COP_MXN(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_MXN", ReplyAction="*")]
        System.Threading.Tasks.Task<double> COP_MXNAsync(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_USD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double COP_USD(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_USD", ReplyAction="*")]
        System.Threading.Tasks.Task<double> COP_USDAsync(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_EUR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double COP_EUR(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COP_EUR", ReplyAction="*")]
        System.Threading.Tasks.Task<double> COP_EURAsync(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_MXN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double EUR_MXN(double EUR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_MXN", ReplyAction="*")]
        System.Threading.Tasks.Task<double> EUR_MXNAsync(double EUR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_USD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double EUR_USD(double EUR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_USD", ReplyAction="*")]
        System.Threading.Tasks.Task<double> EUR_USDAsync(double EUR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_COP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double EUR_COP(double COP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR_COP", ReplyAction="*")]
        System.Threading.Tasks.Task<double> EUR_COPAsync(double COP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConversorMonedaSoapChannel : ClienteSOAP_ConversorMoneda.WSConvertidor.ConversorMonedaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversorMonedaSoapClient : System.ServiceModel.ClientBase<ClienteSOAP_ConversorMoneda.WSConvertidor.ConversorMonedaSoap>, ClienteSOAP_ConversorMoneda.WSConvertidor.ConversorMonedaSoap {
        
        public ConversorMonedaSoapClient() {
        }
        
        public ConversorMonedaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversorMonedaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorMonedaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorMonedaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double MXN_USD(double MXN) {
            return base.Channel.MXN_USD(MXN);
        }
        
        public System.Threading.Tasks.Task<double> MXN_USDAsync(double MXN) {
            return base.Channel.MXN_USDAsync(MXN);
        }
        
        public double MXN_COP(double MXN) {
            return base.Channel.MXN_COP(MXN);
        }
        
        public System.Threading.Tasks.Task<double> MXN_COPAsync(double MXN) {
            return base.Channel.MXN_COPAsync(MXN);
        }
        
        public double MXN_EUR(double MXN) {
            return base.Channel.MXN_EUR(MXN);
        }
        
        public System.Threading.Tasks.Task<double> MXN_EURAsync(double MXN) {
            return base.Channel.MXN_EURAsync(MXN);
        }
        
        public double USD_MXN(double USD) {
            return base.Channel.USD_MXN(USD);
        }
        
        public System.Threading.Tasks.Task<double> USD_MXNAsync(double USD) {
            return base.Channel.USD_MXNAsync(USD);
        }
        
        public double USD_COP(double USD) {
            return base.Channel.USD_COP(USD);
        }
        
        public System.Threading.Tasks.Task<double> USD_COPAsync(double USD) {
            return base.Channel.USD_COPAsync(USD);
        }
        
        public double USD_EUR(double USD) {
            return base.Channel.USD_EUR(USD);
        }
        
        public System.Threading.Tasks.Task<double> USD_EURAsync(double USD) {
            return base.Channel.USD_EURAsync(USD);
        }
        
        public double COP_MXN(double COP) {
            return base.Channel.COP_MXN(COP);
        }
        
        public System.Threading.Tasks.Task<double> COP_MXNAsync(double COP) {
            return base.Channel.COP_MXNAsync(COP);
        }
        
        public double COP_USD(double COP) {
            return base.Channel.COP_USD(COP);
        }
        
        public System.Threading.Tasks.Task<double> COP_USDAsync(double COP) {
            return base.Channel.COP_USDAsync(COP);
        }
        
        public double COP_EUR(double COP) {
            return base.Channel.COP_EUR(COP);
        }
        
        public System.Threading.Tasks.Task<double> COP_EURAsync(double COP) {
            return base.Channel.COP_EURAsync(COP);
        }
        
        public double EUR_MXN(double EUR) {
            return base.Channel.EUR_MXN(EUR);
        }
        
        public System.Threading.Tasks.Task<double> EUR_MXNAsync(double EUR) {
            return base.Channel.EUR_MXNAsync(EUR);
        }
        
        public double EUR_USD(double EUR) {
            return base.Channel.EUR_USD(EUR);
        }
        
        public System.Threading.Tasks.Task<double> EUR_USDAsync(double EUR) {
            return base.Channel.EUR_USDAsync(EUR);
        }
        
        public double EUR_COP(double COP) {
            return base.Channel.EUR_COP(COP);
        }
        
        public System.Threading.Tasks.Task<double> EUR_COPAsync(double COP) {
            return base.Channel.EUR_COPAsync(COP);
        }
    }
}
